### ISSUE TITLE
Running downloadTool in VS2017 agent can't find temp dir

### ISSUE THREAD

**Issue by cdesewell** [Microsoft/azure-pipelines-tool-lib#52]
The agent logs the following error when calling downloadTool
Directory does not exist: `D:\a\_temp\d0ca8410-0ac0-4515-b4cb-ea3dd05e1dd3`

My task source code can be found here:
https://github.com/cdesewell/terragrunt-azure-dev-ops

**Comment by damccorm** [comment]
Edited your comment for clarity because github was escaping the backslashes.

It seems to be working fine for me - [minimal repro](https://github.com/damccorm/terragrunt-azure-dev-ops) and [Succeeding build](https://dev.azure.com/damccorm-repros/terragrunt-azure-dev-ops/_build/results?buildId=70&_a=summary)

Are you running anything before your task? Is it possible that they're somehow deleting the temp dir?

**Comment by cdesewell** [comment]
Hey thanks for your response. I've got it working now.

**Comment by damccorm** [comment]
Ok awesome! I'm going to close, feel free to comment if you'd like to reopen/have other questions
